name: Build and Release

on:
  # push:
  #   branches:
  #     - main  # Executa no push para o branch principal
  workflow_dispatch:
      inputs:
        tipo:
          description: "Tipo de incremento de versão (major, minor, patch)"
          required: false
          default: "minor"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Increment version
        run: |
          tipo_incremento="${{ github.event.inputs.tipo || 'patch' }}"
          python bump_version.py <<< "$tipo_incremento"

      - name: Commit new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Atualiza versão para $(cat VERSION)"
          git push origin main
      
      - name: Debug Release Output
        run: |
          echo "Upload URL: $(cat VERSION)"

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload VERSION artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: VERSION

  build-windows:
    needs: [version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download VERSION artifact
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Read Version
        id: read_version
        shell: cmd
        run: |
          for /F "tokens=*" %%i in (VERSION) do (
            echo VERSION=%%i >> %GITHUB_ENV%
          )

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller -r requirements.txt
      - name: Build for Windows - Versão ${{ env.VERSION }}
        run: python -m PyInstaller --onefile --name=baixar-audio-windows --distpath ./dist/windows/${{ env.VERSION }} ./src/baixar_audio.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/windows/${{ env.VERSION }}/baixar-audio-windows.exe

  build-macos:
    needs: [version]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download VERSION artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyinstaller -r requirements.txt

      - name: Build for macOS Versão ${{ env.VERSION }}
        run: pyinstaller --onefile --name=baixar-audio-mac --distpath ./dist/mac/${{ env.VERSION }} ./src/baixar_audio.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/mac/${{ env.VERSION }}/baixar-audio-mac

  release:
    needs: [version, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: ./dist/windows/${{ env.VERSION }}

      - name: Download macOS Executable
        uses: actions/download-artifact@v4
        with:
          name: macos-executable
          path: ./dist/mac/${{ env.VERSION }}
          
      - name: Read Version
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Set Windows Executable Path
        run: echo "EXEC_WINDOWS=./dist/windows/${{ env.VERSION }}/baixar-audio-windows.exe" >> $GITHUB_ENV

      - name: Set macOS Executable Path
        run: echo "EXEC_MACOS=./dist/mac/${{ env.VERSION }}/baixar-audio-mac" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"  # Use a versão como tag
          release_name: "Versão ${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Debug Release Output
        run: |
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
      
      - name: Upload Windows Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # asset_path: dist/windows/2.0.14/baixar-audio-windows.exe
          # asset_path: ./dist/windows/${{ env.VERSION }}/baixar-audio-windows.exe
          asset_path: ${{ env.EXEC_WINDOWS }}
          asset_name: baixar-audio-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # asset_path: dist/mac/2.0.14/baixar-audio-mac
          # asset_path: ./dist/mac/${{ env.VERSION }}/baixar-audio-mac
          asset_path: ${{ env.EXEC_MACOS }}
          asset_name: baixar-audio-mac
          asset_content_type: application/octet-stream
