name: Release

on:
  # push:
  #   branches:
  #     - main  # Executa no push para o branch principal
  workflow_dispatch:
    inputs:
      tipo:
        description: "Criar release"
        required: false

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Release Output
        run: |
          echo "Tentar coletar os artefatos..."
        
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: ./dist/windows/2.8.0

      - name: Download macOS Executable
        uses: actions/download-artifact@v4
        with:
          name: macos-executable
          path: ./dist/mac/2.8.0
          
      - name: Read Version
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Set Windows Executable Path
        run: echo "EXEC_WINDOWS=./dist/windows/2.8.0/baixar-audio-windows.exe" >> $GITHUB_ENV

      - name: Set macOS Executable Path
        run: echo "EXEC_MACOS=./dist/mac/2.8.0/baixar-audio-mac" >> $GITHUB_ENV
