name: Release

on:
  # push:
  #   branches:
  #     - main  # Executa no push para o branch principal
  workflow_dispatch:
    inputs:
      tipo:
        description: "Criar release"
        required: false

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Release Output
        run: |
          echo "Upload URL: https://uploads.github.com/repos/Eliabegai/download-audio/releases/182817298/assets{?name,label}}"
      - name: Upload Windows Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/Eliabegai/download-audio/releases/182817298/assets{?name,label}
          asset_path: ./dist/windows/2.4.0/baixar-audio-windows
          # asset_path: dist/windows/${{ env.VERSION }}/baixar-audio-windows.exe
          asset_name: baixar-audio-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/Eliabegai/download-audio/releases/182817298/assets{?name,label}
          asset_path: ./dist/mac/2.4.0/baixar-audio-mac
          # asset_path: dist/mac/${{ env.VERSION }}/baixar-audio-mac
          asset_name: baixar-audio-mac
          asset_content_type: application/octet-stream