name: Release

on:
  # push:
  #   branches:
  #     - main  # Executa no push para o branch principal
  workflow_dispatch:
      inputs:
        tipo:
          description: "Tipo de incremento de versão (major, minor, patch)"
          required: false
          default: "patch"

env:
  VERSION:  ${{ github.event.release.tag_name }}

jobs:
  release:
    # needs: [version, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Verificar o código
      run: echo "Iniciando o job de verificação de código! Versão ${{ github.event.inputs.version }}" &&
        echo "Versão= ${{ env.VERSION }} " && echo "Versão= $VERSION "
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.event.inputs.version }}"  # Use a versão como tag
        release_name: "Versão ${{ github.event.inputs.version }}"
        draft: false
        prerelease: false