name: Criar Pasta e Arquivo Executável

on:
#   push:
#     branches:
#       - main  # Executa quando há um push para a branch main
  workflow_dispatch:
      inputs:
        tipo:
          description: "Tipo de incremento de versão (major, minor, patch)"
          required: false
          default: "minor"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Criar pasta
      run: mkdir -p minha_pasta

    - name: Criar arquivo executável
      run: echo "#!/bin/bash" > minha_pasta/meu_script.sh
           echo "echo 'Olá, mundo!'" >> minha_pasta/meu_script.sh
           chmod +x minha_pasta/meu_script.sh

    - name: Compactar a pasta
      run: zip -r minha_pasta.zip minha_pasta

    - name: Fazer upload do arquivo compactado
      uses: actions/upload-artifact@v4
      with:
        name: minha_pasta
        path: minha_pasta.zip
