name: Teste Artefato

on:
  # push:
  #   branches:
  #     - main  # Executa no push para o branch principal
  workflow_dispatch:
      inputs:
        tipo:
          description: "Tipo de incremento de versão (major, minor, patch)"
          required: false
          default: "minor"

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display estrutura de pasta
        run: ls -R
